### ISSUE TITLE
Public release checklist

### ISSUE THREAD

**Issue by curiousdannii** [i7/i7el#1]
- [x] Basic editing
  - [x] Delete extensions
- [x] Public library mode
  - [x] Check for outdated extensions
  - [x] On extension pages offer different install buttons, and check what the current version is
- [x] About page
- [x] Update all dependencies
- [x] Add all former public library files
- [x] Clone settings in the SettingsProxy
